name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tests
    strategy:
      matrix:
        ruby:
          - '3.4.4'
    env:
      TERM: xterm-256color
      RSPEC_COLOR: 'true'
      FORCE_COLOR: '1'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec && bundle exec undercover .
      
      - name: Run rubocop
        run: bundle exec rubocop .